[env:custom_bms_stm32g071]
platform = ststm32
board = nucleo_g071rb
framework = stm32cube

; --- Upload Settings ---
upload_protocol = custom
upload_command = openocd -f interface/stlink.cfg -c "transport select swd" -f target/stm32g0x.cfg -c "program .pio/build/custom_bms_stm32g071/firmware.elf verify reset; shutdown"

; --- Debug Settings ---
debug_tool = custom
debug_server = 
debug_port = localhost:3333

; --- Build Flags ---
build_flags = 
    -Wall
    -Wextra
    -I include
    -D STM32G071xx
    -O0