[env:custom_stm32g071]
platform = ststm32
board = nucleo_g071rb
framework = stm32cube

; --- Upload and Debug Settings ---
upload_protocol = stlink
debug_tool = stlink

; --- Build Flags ---
build_flags = 
    -Wall
    -Wextra